import esbuild from 'esbuild';
import process from 'process';
import builtins from 'builtin-modules';
import sveltePlugin from 'esbuild-svelte';
import sveltePreprocess from 'svelte-preprocess';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: ['obsidian', 'electron', ...builtins],
	format: 'cjs',
	target: 'es2020',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	plugins: [
		sveltePlugin({
			preprocess: sveltePreprocess(),
			compilerOptions: {
				css: 'injected',
				preserveComments: !prod,
			},
		}),
	],
});

if (prod) {
	await context.rebuild();
	await context.dispose();
} else {
	await context.watch();
}
