name: ci
on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          version: 2024.11.3
          install: true
          cache: true # [default: true] cache mise using GitHub's cache
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
  e2e:
    runs-on: macos-latest # macos-14 相当
    env:
      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1" # 先に deps を入れる
    steps:
      - uses: actions/checkout@v4

      - uses: jdx/mise-action@v2
        with:
          version: 2024.11.3
          install: true
          cache: true

      - name: Install Node deps
        run: pnpm install

      - name: Install Playwright browsers (Chromium only)
        run: npx playwright install chromium

      # macOS ランナーには jq がプリインストール
      # 必要なら `brew install jq` も可
      - name: Setup Obsidian & plugin
        run: ./scripts/setup-obsidian.sh --ci
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # ── Playwright セットアップ用のシード test ──
      - name: Run Playwright pre-setup test
        run: npx playwright test tests/e2e-setup/setup.ts --project=e2e-setup

      # ── 本番 E2E ──
      - name: Run full E2E suite
        run: pnpm e2e
