name: ci
on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          version: 2024.11.3
          install: true
          cache: true # [default: true] cache mise using GitHub's cache
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          version: 2024.11.3
          install: true
          cache: true # [default: true] cache mise using GitHub's cache
      - name: Install dependencies
        run: pnpm install
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
      - run: npx playwright install --with-deps chromium

      - name: Setup Obsidian & plugin
        run: |
          sudo apt-get update && sudo apt-get -y install jq
          ./scripts/setup-obsidian.sh --ci
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Playwright tests
        run: |
          xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" -- pnpm e2e:setup
        env:
          OBSIDIAN_BINARY: ${{ github.workspace }}/Obsidian.AppImage
      - if: failure()
        run: |
          pnpm exec playwright show-trace test-results/setup.ts-検索してカードをクリックするとファイルを開ける-e2e-setup/trace.zip
      - name: Run Playwright tests
        run: |
          xvfb-run --auto-servernum -- Obsidian.AppImage --version
          pnpm e2e
