name: ci
on:
  workflow_dispatch:
#  pull_request:
#  push:
#    branches: ["main"]
#  schedule:
#    - cron: "0 18 * * *" # JST 3:00（UTC 18:00）

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac # v2.4.4
        with:
          version: 2024.11.3
          install: true
          cache: true # [default: true] cache mise using GitHub's cache
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build

  e2e:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac # v2.4.4
        with:
          version: 2024.11.3
          install: true
          cache: true
      - run: pnpm install
      - run: ./scripts/setup-obsidian.sh --ci
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: pnpm e2e:setup
      - run: pnpm e2e

  test-e2e-tools:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac # v2.4.4
        with:
          version: 2024.11.3
          install: true
          cache: true
      - run: pnpm install
      - run: ./scripts/setup-obsidian.sh --ci
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: pnpm e2e:setup
      - run: pnpm e2e:cleanup
