name: ci
on:
  pull_request:
  push:
    branches: ["main"]
  schedule:
    - cron: "0 18 * * *" # JST 3:00（UTC 18:00）

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          version: 2024.11.3
          install: true
          cache: true # [default: true] cache mise using GitHub's cache
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build

  e2e:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          version: 2024.11.3
          install: true
          cache: true
      - run: pnpm install
      - run: ./scripts/setup-obsidian.sh --ci
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: pnpm e2e:setup
      - run: pnpm e2e

  test-e2e-tools:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          version: 2024.11.3
          install: true
          cache: true
      - run: pnpm install
      - run: ./scripts/setup-obsidian.sh --ci
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: pnpm e2e:setup
      - run: pnpm e2e:cleanup
